ROOT_PATH=/home/vijay

COMPILER_PATH=/opt/crosstool/gcc-4.0.2-glibc-2.3.2/arm-unknown-linux-gnu/bin/arm-unknown-linux-gnu-
CC=$(COMPILER_PATH)gcc
INCLUDE_PATH=$(ROOT_PATH)/proj/base/kernel/linux-2.6.21-ts/include/linux


all: htest

clean:
	rm *.o htest

