COMPILER_PATH=/home/vijay/toobo/toobo/toolchains/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-
CC=$(COMPILER_PATH)gcc

KERNELDIR ?= /home/vijay/toobo/toobo/kernel/linux-2.6

INCLUDE_PATH=$(KERNELDIR)/include/linux


all: htest

clean:
	rm *.o htest

