ROOT_PATH=/home/vijay

COMPILER_PATH=/opt/crosstool/gcc-4.0.2-glibc-2.3.2/arm-unknown-linux-gnu/bin/arm-unknown-linux-gnu-
CC=$(COMPILER_PATH)gcc
INCLUDE_PATH=$(ROOT_PATH)/proj/base/kernel/linux-2.6.21-ts/include/linux

#INCLUDE_PATH=/usr/src/linux

#all: display-test.o
#	$(CC) -o display-test display-test.o

#display-test.o: display-test.c
#	$(CC) -o display-test.o -c display-test.c

all: display-test

clean:
	rm *.o display-test
