# -*-python-*-
#
# [Sconscript] [Part of the TOOBO Project]
# 
# Copyright 2008 Vijay Jayaraman (osembedded@gmail.com) 
# 
# This program is free software: you can redistribute it and/or modify 
# it under the terms of the GNU Lesser General Public License as published by 
# the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
# GNU Lesser General Public License for more details. 
# 
# You should have received a copy of the GNU Lesser General Public License 
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#import os
#path = ['/opt/crosstool/gcc-3.3.4-glibc-2.3.2/bin']
#env = Environment(ENV = os.environ,
#                  CC="arm-linux-gcc",
#                  LD="arm-linux-ld")

Import('env')

#print "CC is: ", env['CC']
#print "ENV is: ", env['ENV']

env.Program('startupMgr', 'startupMgr_p.c')
